application:
  name: 'Scyon Juice Shop'
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  theme: indigo-pink
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: false
  welcomeBanner:
    showOnFirstStart: false
  social:
    twitterUrl: 'https://twitter.com/ScyonSecurity'
    facebookUrl: null
    slackUrl: null
    redditUrl: null
    pressKitUrl: null
    nftUrl: null
    questionnaireUrl: null
challenges:
  showHints: true
  showFeedbackButtons: false
  safetyMode: enabled
  enabledCategories:
    - Broken Access Control
    - Broken Anti Automation
    - Broken Authentication
    - Cryptographic Issues
    - Improper Input Validation
    - Insecure Deserialization
    - Injection
    - Miscellaneous
#    - Security Misconfiguration
#    - Security through Obscurity
#    - Sensitive Data Exposure
#    - Unvalidated Redirects
    - Vulnerable Components
    - XSS
    - XXE
hackingInstructor:
  isEnabled: true
ctf:
  showFlagsInNotifications: true
