application:
  name: 'Scyon Juice Shop'
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  theme: indigo-pink
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: false
  welcomeBanner:
    showOnFirstStart: false
  social:
    twitterUrl: 'https://twitter.com/ScyonSecurity'
    facebookUrl: null
    slackUrl: null
    redditUrl: null
    pressKitUrl: null
    nftUrl: null
    questionnaireUrl: null
challenges:
  showHints: true
  showFeedbackButtons: false
  safetyMode: enabled
  categories:
    - category: Broken Access Control
      enabled: true
    - category: Broken Anti Automation
      enabled: true
    - category: Broken Authentication
      enabled: true
    - category: Cryptographic Issues
      enabled: true
    - category: Improper Input Validation
      enabled: true
    - category: Insecure Deserialization
      enabled: true
    - category: Injection
      enabled: false
    - category: Miscellaneous
      enabled: true
    - category: Security Misconfiguration
      enabled: false
    - category: Security through Obscurity
      enabled: true
    - category: Sensitive Data Exposure
      enabled: true
    - category: Unvalidated Redirects
      enabled: true
    - category: Vulnerable Components
      enabled: true
    - category: XSS
      enabled: true
    - category: XXE
      enabled: true
hackingInstructor:
  isEnabled: true
ctf:
  showFlagsInNotifications: true
