application:
  name: 'Scyon Juice Shop'
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  theme: indigo-pink
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: false
  welcomeBanner:
    showOnFirstStart: false
  social:
    twitterUrl: 'https://twitter.com/ScyonSecurity'
    facebookUrl: null
    slackUrl: null
    redditUrl: null
    pressKitUrl: null
    nftUrl: null
    questionnaireUrl: null
challenges:
  showHints: true
  showFeedbackButtons: false
  safetyMode: enabled
  enabledCategories:
    - challengeCategory: Broken Access Control
      enabled: true
    - challengeCategory: Broken Anti Automation
      enabled: true
    - challengeCategory: Broken Authentication
      enabled: true
    - challengeCategory: Cryptographic Issues
      enabled: true
    - challengeCategory: Improper Input Validation
      enabled: true
    - challengeCategory: Insecure Deserialization
      enabled: true
    - challengeCategory: Injection
      enabled: false
    - challengeCategory: Miscellaneous
      enabled: true
    - challengeCategory: Security Misconfiguration
      enabled: false
    - challengeCategory: Security through Obscurity
      enabled: true
    - challengeCategory: Sensitive Data Exposure
      enabled: true
    - challengeCategory: Unvalidated Redirects
      enabled: true
    - challengeCategory: Vulnerable Components
      enabled: true
    - challengeCategory: XSS
      enabled: true
    - challengeCategory: XXE
      enabled: true
hackingInstructor:
  isEnabled: true
ctf:
  showFlagsInNotifications: true
